//Authentication
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAIL = 'LOGINFAIL';
export const REGISTERSUCCESS = 'REGISTERSUCCESS';
export const REGISTERFAIL = 'REGISTERFAIL';
export const LOGOUT = 'LOGOUT';
export const LOADUSER = 'LOADUSER';

//Event
export const EVENTCREATESUCCESS = 'EVENTCREATESUCCESS';
export const EVENTDELETESUCCESS = 'EVENTDELETESUCCESS';
export const EVENTUPDATESUCCESS = 'EVENTUPDATESUCCESS';
export const LOADEVENT = 'LOADEVENT';
export const FILTEREVENT = 'FILTEREVENT';

//Category
export const CATEGORYCREATESUCCESS = 'CATEGORYCREATESUCCESS';
export const CATEGORYDELETESUCCESS = 'CATEGORYDELETESUCCESS';
export const CATEGORYUPDATESUCCESS = 'CATEGORYUPDATESUCCESS';
export const LOADCATEGORY = 'LOADCATEGORY';

//Message Alert

export const SETMESSAGEALERT = 'SETMESSAGEALERT';
export const REMOVEMESSAGEALERT = 'REMOVEMESSAGEALERT';
